language: android
sudo: required
dist: trusty
android:
  components:
  - build-tools-29.0.2
  - android-29
  - tools
  - platform-tools
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-google_play_services
before_install:
  - chmod +x gradlew
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
script:
    - ./gradlew androidDependencies
    - ./gradlew build
