language: android
sudo: required
dist: trusty

branches:
  only:
  - master
  - dev

android:
  components:
  - build-tools-29.0.2
  - android-29
  - tools
  - tools
  - platform-tools
  lisences:
  - android-sdk-license-.+
  
before_install:
  - chmod +x gradlew
  - yes | sdkmanager --update
  - yes | sdkmanager --licenses
  
script:
  - "./gradlew androidDependencies clean build test"
  
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache

notifications:
  slack:
    on_success: always
    slack: awesomeplanb:pwlilBY08nuCZqbCTX09meOq
  email:
    recipients:
      - dikolight203@gmail.com
    on_success: never
    on_failure: always
    

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file: "app/build/outputs/apk/release/app-release.apk"
  api_key: ad7ce99d5dc4492b3a9cdb3b6b363620e295a70e
  on:
    branch:
      - master
